using Microsoft.EntityFrameworkCore;

namespace CarAds.Models
{
    public class CarAdsContext : DbContext
    {
        public CarAdsContext()
        {

        }

        public CarAdsContext(DbContextOptions<CarAdsContext> options) : base(options)
        {

        }

        public DbSet<ModelEntity> Models { get; set; }
        public DbSet<BrandEntity> Brands { get; set; }
        public DbSet<PersonEntity> Persons { get; set; }
        public DbSet<CarEntity> Cars { get; set; }
        public DbSet<BodyEntity> Bodies { get; set; }
        public DbSet<FuelEntity> Fuels { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();
            optionsBuilder.UseSqlServer(configuration.GetConnectionString("PrimaryConnectionString"));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            int id = 1;
            modelBuilder.Entity<ModelEntity>()
                .HasData(
                    new ModelEntity { Id = id++, ModelName = "Alhambra", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Altea", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Altea XL", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Arosa", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Cordoba", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Cordoba Vario", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Exeo", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Ibiza", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Ibiza ST", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Exeo ST", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Leon", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Leon ST", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Inca", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Mii", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Toledo", BrandId = 1 },
                    new ModelEntity { Id = id++, ModelName = "Captur", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Clio", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Clio Grandtour", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Espace", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Express", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Grand Espace", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Grand Modus", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Grand Scenic", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Kadjar", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Kangoo", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Kangoo Express", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Koleos", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Laguna", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Laguna Grandtour", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Latitude", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mascott", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mégane", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mégane CC", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mégane CC", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mégane Grandtour", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mégane Coupé", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Mégane Scénic", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Scénic", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Talisman", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Talisman Grandtour", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Thalia", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Twingo", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Wind", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "Zoé", BrandId = 2 },
                    new ModelEntity { Id = id++, ModelName = "1007", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "107", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "106", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "108", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "2008", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "205", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "205 Cabrio", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "206", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "206 CC", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "206 SW", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "207", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "207 CC", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "207 SW", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "306", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "307", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "307 CC", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "307 SW", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "308", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "308 CC", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "308 SW", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "309", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "4007", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "4008", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "405", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "406", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "407", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "407 SW", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "5008", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "508", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "508 SW", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "605", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "806", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "607", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "807", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "Bipper", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "RCZ", BrandId = 3 },
                    new ModelEntity { Id = id++, ModelName = "Dokker", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Duster", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Lodgy", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Logan", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Logan MCV", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Logan Van", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Sandero", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Solenza", BrandId = 4 },
                    new ModelEntity { Id = id++, ModelName = "Berlingo", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C-Crosser", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C-Elissée", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C-Zero", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C1", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C2", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C3", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C3 Picasso", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C4", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C4 Aircross", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C4 Cactus", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C4 Coupé", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C4 Grand Picasso", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C4 Sedan", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C5", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C5 Break", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C5 Tourer", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C6", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "C8", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "DS3", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "DS4", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "DS5", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Evasion", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Jumper", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Jumpy", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Saxo", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Nemo", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Xantia", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Xsara", BrandId = 5 },
                    new ModelEntity { Id = id++, ModelName = "Agila", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Ampera", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Antara", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Astra", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Astra cabrio", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Astra caravan", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Astra coupé", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Calibra", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Campo", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Cascada", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Corsa", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Frontera", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Insignia", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Insignia kombi", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Kadett", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Meriva", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Mokka", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Movano", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Omega", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Signum", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Vectra", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Vectra Caravan", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Vivaro", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Vivaro Kombi", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "Zafira", BrandId = 6 },
                    new ModelEntity { Id = id++, ModelName = "145", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "146", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "147", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "155", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "156", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "156 Sportwagon", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "159", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "159 Sportwagon", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "164", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "166", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "4C", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "Brera", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "GTV", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "MiTo", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "Crosswagon", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "Spider", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "GT", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "Giulietta", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "Giulia", BrandId = 7 },
                    new ModelEntity { Id = id++, ModelName = "Favorit", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Felicia", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Citigo", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Fabia", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Fabia Combi", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Fabia Sedan", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Felicia Combi", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Octavia", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Octavia Combi", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Roomster", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Yeti", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Rapid", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Rapid Spaceback", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Superb", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Superb Combi", BrandId = 8 },
                    new ModelEntity { Id = id++, ModelName = "Alero", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Aveo", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Camaro", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Captiva", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Corvette", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Cruze", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Cruze SW", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Epica", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Equinox", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Evanda", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "HHR", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Kalos", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Lacetti", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Lacetti SW", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Lumina", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Malibu", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Matiz", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Monte Carlo", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Nubira", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Orlando", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Spark", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Suburban", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Tacuma", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Tahoe", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Trax", BrandId = 9 },
                    new ModelEntity { Id = id++, ModelName = "Accord", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Accord Coupé", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Accord Tourer", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "City", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Civic", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Civic Aerodeck", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Civic Coupé", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Civic Tourer", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Civic Type R", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "CR-V", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "CR-X", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "CR-Z", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "FR-V", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "HR-V", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Insight", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Integra", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Jazz", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Legend", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "Prelude", BrandId = 10 },
                    new ModelEntity { Id = id++, ModelName = "911 Carrera", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "911 Carrera Cabrio", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "911 Targa", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "911 Turbo", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "924", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "944", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "997", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "Boxster", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "Cayenne", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "Cayman", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "Macan", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "Panamera", BrandId = 11 },
                    new ModelEntity { Id = id++, ModelName = "BRZ", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Forester", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Impreza", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Impreza Wagon", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Justy", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Legacy", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Legacy Wagon", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Legacy Outback", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Levorg", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Outback", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "SVX", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Tribeca", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "Tribeca B9", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "XV", BrandId = 12 },
                    new ModelEntity { Id = id++, ModelName = "121", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "2", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "3", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "323", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "323 Combi", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "323 Coupé", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "323 F", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "5", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "6", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "6 Combi", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "626", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "626 Combi", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "B-Fighter", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "B2500", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "BT", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "CX-3", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "CX-5", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "CX-7", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "CX-9", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "Demio", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "MPV", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "MX-3", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "MX-5", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "MX-6", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "Premacy", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "RX-7", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "RX-8", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "Xedox 6", BrandId = 13 },
                    new ModelEntity { Id = id++, ModelName = "3000 GT", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "ASX", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Carisma", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Colt", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Colt CC", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Eclipse", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Fuso canter", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Galant", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Galant Combi", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Grandis", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "L200", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "L200 Pick up", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "L200 Pick up Allrad", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "L300", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Lancer", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Lancer Combi", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Lancer Evo", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Lancer Sportback", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Outlander", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Pajero", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Pajeto Pinin", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Pajero Pinin Wagon", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Pajero Sport", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Pajero Wagon", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "Space Star", BrandId = 14 },
                    new ModelEntity { Id = id++, ModelName = "CT", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "GS", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "GS 300", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "GX", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "IS", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "IS 200", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "IS 250 C", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "IS-F", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "LS", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "LX", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "NX", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "RC F", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "RX", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "RX 300", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "RX 400h", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "RX 450h", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "SC 430", BrandId = 15 },
                    new ModelEntity { Id = id++, ModelName = "4-Runner", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Auris", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Avensis", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Avensis Combi", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Avensis Van Verso", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Aygo", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Camry", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Carina", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Celica", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Corolla", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Corolla Combi", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Corolla sedan", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Corolla Verso", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "FJ Cruiser", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "GT86", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Hiace", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Hiace Van", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Highlander", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Hilux", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Land Cruiser", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "MR2", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Paseo", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Picnic", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Prius", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "RAV4", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Sequoia", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Starlet", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Supra", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Tundra", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Urban Cruiser", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Verso", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Yaris", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "Yaris Verso", BrandId = 16 },
                    new ModelEntity { Id = id++, ModelName = "i3", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "i8", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "M3", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "M4", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "M5", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "M6", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 1", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 1 Cabrio", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 1 Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 2", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 2 Active Tourer", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 2 Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 2 Gran Tourer", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 3", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 3 Cabrio", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 3 Compact", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 3 Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 3 GT", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 3 Touring", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 4", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 4 Cabrio", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 4 Gran Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 5", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 5 GT", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 5 Touring", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 6", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 6 Cabrio", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 6 Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 6 Gran Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 7", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Rad 8 Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "X1", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "X3", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "X4", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "X5", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "X6", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Z3", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Z3 Coupé", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Z3 Roadster", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Z4", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Z4 Roadster", BrandId = 17 },
                    new ModelEntity { Id = id++, ModelName = "Amarok", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Beetle", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Bora", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Bora Variant", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Caddy", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Caddy Van", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Life", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "California", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Caravelle", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "CC", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Crafter", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Crafter Van", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Crafter Kombi", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "CrossTouran", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Eos", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Fox", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Golf", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Golf Cabrio", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Golf Plus", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Golf Sportvan", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Golf Variant", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Jetta", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "LT", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Lupo", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Multivan", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "New Beetle", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "New Beetle Cabrio", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Passat", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Passat Alltrack", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Passat CC", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Passat Variant", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Passat Variant Van", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Phaeton", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Polo", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Polo Van", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Polo Variant", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Scirocco", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Sharan", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T4", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T4 Caravelle", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T4 Multivan", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T5", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T5 Caravelle", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T5 Multivan", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "T5 Transporter Shuttle", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Tiguan", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Touareg", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Touran", BrandId = 18 },
                    new ModelEntity { Id = id++, ModelName = "Alto", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Baleno", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Baleno kombi", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Grand Vitara", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Grand Vitara XL-7", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Ignis", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Jimny", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Kizashi", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Liana", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Samurai", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Splash", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Swift", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "SX4", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "SX4 Sedan", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Vitara", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "Wagon R+", BrandId = 19 },
                    new ModelEntity { Id = id++, ModelName = "100 D", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "115", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "124", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "126", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "190", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "190 D", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "190 E", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "200 - 300", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "200 D", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "200 E", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "210 Van", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "210 kombi", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "310 Van", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "310 kombi", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "230 - 300 CE Coupé", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "260 - 560 SE", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "260 - 560 SEL", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "500 - 600 SEC Coupé", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda A", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "A", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "A L", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "AMG GT", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda B", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda C", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "C", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "C Sportcoupé", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "C T", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Citan", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CL", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CL", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CLA", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CLC", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CLK Cabrio", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CLK Coupé", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "CLS", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda E", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "E", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "E Cabrio", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "E Coupé", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "E T", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda G", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "G Cabrio", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "GL", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "GLA", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "GLC", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "GLE", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "GLK", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda M", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "MB 100", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda R", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Trieda S", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "S", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "S Coupé", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "SL", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "SLC", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "SLK", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "SLR", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "Sprinter", BrandId = 20 },
                    new ModelEntity { Id = id++, ModelName = "9-3", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "9-3 Cabriolet", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "9-3 Coupé", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "9-3 SportCombi", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "9-5", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "9-5 SportCombi", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "900", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "900 C", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "900 C Turbo", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "9000", BrandId = 21 },
                    new ModelEntity { Id = id++, ModelName = "100", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "100 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "80", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "80 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "80 Cabrio", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "90", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A1", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A2", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A3", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A3 Cabriolet", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A3 Limuzina", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A3 Sportback", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A4", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A4 Allroad", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A4 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A4 Cabriolet", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A5", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A5 Cabriolet", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A5 Sportback", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A6", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A6 Allroad", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A6 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A7", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A8", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "A8 Long", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "Q3", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "Q5", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "Q7", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "R8", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "RS4 Cabriolet", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "RS4/RS4 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "RS5", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "RS6 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "RS7", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S3/S3 Sportback", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S4 Cabriolet", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S4/S4 Avant", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S5/S5 Cabriolet", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S6/RS6", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S7", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "S8", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "SQ5", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "TT Coupé", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "TT Roadster", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "TTS", BrandId = 22 },
                    new ModelEntity { Id = id++, ModelName = "Avella", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Besta", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Carens", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Carnival", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Cee`d", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Cee`d SW", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Cerato", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "K 2500", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Magentis", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Opirus", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Optima", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Picanto", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Pregio", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Pride", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Pro Cee`d", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Rio", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Rio Combi", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Rio sedan", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Sephia", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Shuma", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Sorento", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Soul", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Sportage", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "Venga", BrandId = 23 },
                    new ModelEntity { Id = id++, ModelName = "109", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Defender", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Discovery", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Discovery Sport", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Freelander", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Range Rover", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Range Rover Evoque", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Range Rover Sport", BrandId = 24 },
                    new ModelEntity { Id = id++, ModelName = "Avenger", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Caliber", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Challenger", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Charger", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Grand Caravan", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Journey", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Magnum", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Nitro", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "RAM", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Stealth", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "Viper", BrandId = 25 },
                    new ModelEntity { Id = id++, ModelName = "300 C", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "300 C Touring", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "300 M", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Crossfire", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Grand Voyager", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "LHS", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Neon", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Pacifica", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Plymouth", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "PT Cruiser", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Sebring", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Sebring Convertible", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Stratus", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Stratus Cabrio", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Town & Country", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Voyager", BrandId = 26 },
                    new ModelEntity { Id = id++, ModelName = "Aerostar", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "B-Max", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "C-Max", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Cortina", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Cougar", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Edge", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Escort", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Escort Cabrio", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Escort kombi", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Explorer", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "F-150", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "F-250", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Fiesta", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Focus", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Focus C-Max", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Focus CC", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Focus kombi", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Fusion", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Galaxy", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Grand C-Max", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Ka", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Kuga", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Maverick", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Mondeo", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Mondeo Combi", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Mustang", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Orion", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Puma", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Ranger", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "S-Max", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Sierra", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Street Ka", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Tourneo Connect", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Tourneo Custom", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Bus", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Connect LWB", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Courier", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Custom", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit kombi", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Tourneo", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Valnik", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Van", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Transit Van 350", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "Windstar", BrandId = 27 },
                    new ModelEntity { Id = id++, ModelName = "H2", BrandId = 28 },
                    new ModelEntity { Id = id++, ModelName = "H3", BrandId = 28 },
                    new ModelEntity { Id = id++, ModelName = "Accent", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Atos", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Atos Prime", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Coupé", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Elantra", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Galloper", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Genesis", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Getz", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Grandeur", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "H 350", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "H1", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "H1 Bus", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "H1 Van", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "H200", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "i10", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "i20", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "i30", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "i30 CW", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "i40", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "i40 CW", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "ix20", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "ix35", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "ix55", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Lantra", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Matrix", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Santa Fe", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Sonata", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Terracan", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Trajet", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Tucson", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "Veloster", BrandId = 29 },
                    new ModelEntity { Id = id++, ModelName = "EX", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "FX", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "G", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "G Coupé", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "M", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "Q", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "QX", BrandId = 30 },
                    new ModelEntity { Id = id++, ModelName = "Daimler", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "F-Pace", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "F-Type", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "S-Type", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "Sovereign", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "X-Type", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "X-type Estate", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XE", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XF", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XJ", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XJ12", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XJ6", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XJ8", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XJ8", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XJR", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XK", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XK8 Convertible", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XKR", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "XKR Convertible", BrandId = 31 },
                    new ModelEntity { Id = id++, ModelName = "100 NX", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "200 SX", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "350 Z", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "350 Z Roadster", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "370 Z", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Almera", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Almera Tino", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Cabstar E - T", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Cabstar TL2 Valnik", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "e-NV200", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "GT-R", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Insterstar", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Juke", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "King Cab", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Leaf", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Maxima", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Maxima QX", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Micra", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Murano", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Navara", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Note", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "NP300 Pickup", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "NV200", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "NV400", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Pathfinder", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Patrol", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Patrol GR", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Pickup", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Pixo", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Primastar", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Primastar Combi", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Primera", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Primera Combi", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Pulsar", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Qashqai", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Serena", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Sunny", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Terrano", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Tiida", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Trade", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Vanette Cargo", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "X-Trail", BrandId = 32 },
                    new ModelEntity { Id = id++, ModelName = "Cherokee", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "Commander", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "Compass", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "Grand Cherokee", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "Patriot", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "Renegade", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "Wrangler", BrandId = 33 },
                    new ModelEntity { Id = id++, ModelName = "240", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "340", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "360", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "460", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "850", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "850 kombi", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "C30", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "C70", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "C70 Cabrio", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "C70 Coupé", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "S40", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "S60", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "S70", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "S80", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "S90", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "V40", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "V50", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "V60", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "V70", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "V90", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "XC60", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "XC70", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "XC90", BrandId = 34 },
                    new ModelEntity { Id = id++, ModelName = "Espero", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Kalos", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Lacetti", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Lanos", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Leganza", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Lublin", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Matiz", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Nexia", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Nubira", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Nubira kombi", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Racer", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Tacuma", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "Tico", BrandId = 35 },
                    new ModelEntity { Id = id++, ModelName = "1100", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "126", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "500", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "500L", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "500X", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "850", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Barchetta", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Brava", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Cinquecento", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Coupé", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Croma", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Doblo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Doblo Cargo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Doblo Cargo Combi", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Ducato", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Ducato Van", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Ducato Kombi", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Ducato Podvozok", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Florino", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Florino Combi", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Freemont", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Grande Punto", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Idea", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Linea", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Marea", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Marea Weekend", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Multipla", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Palio Weekend", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Panda", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Panda Van", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Punto", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Punto Cabriolet", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Punto Evo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Punto Van", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Qubo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Scudo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Scudo Van", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Scudo Kombi", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Sedici", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Seicento", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Stilo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Stilo Multiwagon", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Strada", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Talento", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Tipo", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Ulysse", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Uno", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "X1/9", BrandId = 36 },
                    new ModelEntity { Id = id++, ModelName = "Cooper", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper Cabrio", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper Clubman", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper D", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper D Clubman", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper S", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper S Cabrio", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Cooper S Clubman", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Countryman", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "Mini One", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "One D", BrandId = 37 },
                    new ModelEntity { Id = id++, ModelName = "200", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "214", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "218", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "25", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "400", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "414", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "416", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "620", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "75", BrandId = 38 },
                    new ModelEntity { Id = id++, ModelName = "Cabrio", BrandId = 39 },
                    new ModelEntity { Id = id++, ModelName = "City-Coupé", BrandId = 39 },
                    new ModelEntity { Id = id++, ModelName = "Compact Pulse", BrandId = 39 },
                    new ModelEntity { Id = id++, ModelName = "Forfour", BrandId = 39 },
                    new ModelEntity { Id = id++, ModelName = "Fortwo cabrio", BrandId = 39 },
                    new ModelEntity { Id = id++, ModelName = "Fortwo coupé", BrandId = 39 },
                    new ModelEntity { Id = id, ModelName = "Roadster", BrandId = 39 }
                );

            id = 1;
            modelBuilder.Entity<BrandEntity>()
                .HasData(
                    new BrandEntity { Id = id++, BrandName = "Seat" },
                    new BrandEntity { Id = id++, BrandName = "Renault" },
                    new BrandEntity { Id = id++, BrandName = "Peugeot" },
                    new BrandEntity { Id = id++, BrandName = "Dacia" },
                    new BrandEntity { Id = id++, BrandName = "Citroen" },
                    new BrandEntity { Id = id++, BrandName = "Opel" },
                    new BrandEntity { Id = id++, BrandName = "Alfa Romeo" },
                    new BrandEntity { Id = id++, BrandName = "Škoda" },
                    new BrandEntity { Id = id++, BrandName = "Chevrolet" },
                    new BrandEntity { Id = id++, BrandName = "Honda" },
                    new BrandEntity { Id = id++, BrandName = "Porsche" },
                    new BrandEntity { Id = id++, BrandName = "Subaru" },
                    new BrandEntity { Id = id++, BrandName = "Mazda" },
                    new BrandEntity { Id = id++, BrandName = "Mitsubishi" },
                    new BrandEntity { Id = id++, BrandName = "Lexus" },
                    new BrandEntity { Id = id++, BrandName = "Toyota" },
                    new BrandEntity { Id = id++, BrandName = "BMW" },
                    new BrandEntity { Id = id++, BrandName = "Volkswagen" },
                    new BrandEntity { Id = id++, BrandName = "Suzuki" },
                    new BrandEntity { Id = id++, BrandName = "Mercedes-Benz" },
                    new BrandEntity { Id = id++, BrandName = "Saab" },
                    new BrandEntity { Id = id++, BrandName = "Audi" },
                    new BrandEntity { Id = id++, BrandName = "Kia" },
                    new BrandEntity { Id = id++, BrandName = "Land Rover" },
                    new BrandEntity { Id = id++, BrandName = "Dodge" },
                    new BrandEntity { Id = id++, BrandName = "Chrysler" },
                    new BrandEntity { Id = id++, BrandName = "Ford" },
                    new BrandEntity { Id = id++, BrandName = "Hummer" },
                    new BrandEntity { Id = id++, BrandName = "Hyundai" },
                    new BrandEntity { Id = id++, BrandName = "Infiniti" },
                    new BrandEntity { Id = id++, BrandName = "Jaguar" },
                    new BrandEntity { Id = id++, BrandName = "Nisan" },
                    new BrandEntity { Id = id++, BrandName = "Jeep" },
                    new BrandEntity { Id = id++, BrandName = "Volvo" },
                    new BrandEntity { Id = id++, BrandName = "Daewoo" },
                    new BrandEntity { Id = id++, BrandName = "Fiat" },
                    new BrandEntity { Id = id++, BrandName = "MINI" },
                    new BrandEntity { Id = id++, BrandName = "Rover" },
                    new BrandEntity { Id = id, BrandName = "Smart" }
                );

            id = 1;
            modelBuilder.Entity<BodyEntity>()
                .HasData(
                    new BodyEntity { Id = id++, BodyName = "Limousine" },
                    new BodyEntity { Id = id++, BodyName = "Hatchback" },
                    new BodyEntity { Id = id++, BodyName = "Caravan" },
                    new BodyEntity { Id = id++, BodyName = "Cupe" },
                    new BodyEntity { Id = id++, BodyName = "Cabriolet / Roadster" },
                    new BodyEntity { Id = id++, BodyName = "Minivan" },
                    new BodyEntity { Id = id++, BodyName = "SUV" },
                    new BodyEntity { Id = id, BodyName = "Pickup" }
                );

            id = 1;
            modelBuilder.Entity<FuelEntity>()
                .HasData(
                    new FuelEntity { Id = id++, FuelType = "Gasoline" },
                    new FuelEntity { Id = id++, FuelType = "Diesel" },
                    new FuelEntity { Id = id++, FuelType = "Electric" },
                    new FuelEntity { Id = id++, FuelType = "Hybrid" },
                    new FuelEntity { Id = id++, FuelType = "TNG" },
                    new FuelEntity { Id = id++, FuelType = "CNG" }
                );
        }
    }
}
